// ***********************************************************************
// Assembly         : Zeroit.Framework.Utilities
// Author           : ZEROIT
// Created          : 11-22-2018
//
// Last Modified By : ZEROIT
// Last Modified On : 12-21-2018
// ***********************************************************************
// <copyright file="_ColorFunctionalities.cs" company="Zeroit Dev Technologies">
//    This program contains Utilities for all C# programming activities.
//    Copyright ©  2017  Zeroit Dev Technologies
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
//    You can contact me at zeroitdevnet@gmail.com or zeroitdev@outlook.com
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Collections.Generic;
using System.Drawing;

namespace ZeroitDevColorPicker.Helpers.Colors.WikiColors
{
    /// <summary>
    /// Class WebColor.
    /// </summary>
    public static partial class WebColor
    {

        #region Private Fields


        /// <summary>
        /// The colors a
        /// </summary>
        private static readonly Dictionary<string, Color> allColors = new Dictionary<string, Color>()
        {
            { "Absolute Zero", AbsoluteZero},
            { "Acajou", Acajou},
            { "Acid Green", AcidGreen},
            { "Aero", Aero},
            { "Aero Blue", AeroBlue},
            { "African Violet", AfricanViolet},
            { "AirForce Blue USAF", AirForceBlueUSAF},
            { "Air Superiority Blue", AirSuperiorityBlue},
            { "Alabama Crimson", AlabamaCrimson},
            { "Alabaster", Alabaster},
            { "Alice Blue", AliceBlue},
            { "Alien Armpit", AlienArmpit},
            { "Alizarin Crimson", AlizarinCrimson},
            { "Alloy Orange", AlloyOrange},
            { "Almond", Almond},
            { "Amaranth", Amaranth},
            { "Amaranth Deep Purple", AmaranthDeepPurple},
            { "Amaranth Pink", AmaranthPink},
            { "Amaranth Purple", AmaranthPurple},
            { "Amaranth Red", AmaranthRed},
            { "Amazon", Amazon},
            { "Amazonite", Amazonite},
            { "Amber", Amber},
            { "Amber SAEECE", AmberSAEECE},
            { "American Blue", AmericanBlue},
            { "American Bronze", AmericanBronze},
            { "American Brown", AmericanBrown},
            { "American Gold", AmericanGold},
            { "American Green", AmericanGreen},
            { "American Orange", AmericanOrange},
            { "American Pink", AmericanPink},
            { "American Purple", AmericanPurple},
            { "American Red", AmericanRed},
            { "American Rose", AmericanRose},
            { "American Silver", AmericanSilver},
            { "American Violet", AmericanViolet},
            { "American Yellow", AmericanYellow},
            { "Amethyst", Amethyst},
            { "Android Green", AndroidGreen},
            { "Anti-Flash White", AntiFlashWhite},
            { "Antique Brass", AntiqueBrass},
            { "Antique Bronze", AntiqueBronze},
            { "Antique Fuchsia", AntiqueFuchsia},
            { "Antique Ruby", AntiqueRuby},
            { "Antique White", AntiqueWhite},
            { "AoEnglish", AoEnglish},
            { "Apple", Apple},
            { "Apple Green", AppleGreen},
            { "Apricot", Apricot},
            { "Aqua", Aqua},
            { "Aquamarine", Aquamarine},
            { "Arctic Lime", ArcticLime},
            { "Army Green", ArmyGreen},
            { "Arsenic", Arsenic},
            { "Artichoke", Artichoke},
            { "Arylide Yellow", ArylideYellow},
            { "AshGray", AshGray},
            { "Asparagus", Asparagus},
            { "Ateneo Blue", AteneoBlue},
            { "Atomic Tangerine", AtomicTangerine},
            { "Auburn", Auburn},
            { "Aureolin", Aureolin},
            { "Auro Metal Saurus", AuroMetalSaurus},
            { "Avocado", Avocado},
            { "Awesome", Awesome},
            { "Axolotl", Axolotl},
            { "Aztec Gold", AztecGold},
            { "Azure", Azure},
            { "Azure Web", AzureWeb},
            { "Azure Mist", AzureMist},
            { "Azureish White", AzureishWhite},

            { "Baby Blue", BabyBlue},
            { "Baby Blue Eyes", BabyBlueEyes},
            { "Baby Pink", BabyPink},
            { "Baby Powder", BabyPowder},
            { "Baker Miller Pink", BakerMillerPink},
            { "Ball Blue", BallBlue},
            { "Banana Mania", BananaMania},
            { "Banana Yellow", BananaYellow},
            { "Bangladesh Green", BangladeshGreen},
            { "Barbie Pink", BarbiePink},
            { "Barn Red", BarnRed},
            { "Battery Charged Blue", BatteryChargedBlue},
            { "Battleship Grey", BattleshipGrey},
            { "Bazaar", Bazaar},
            { "Beau Blue", BeauBlue},
            { "Beaver", Beaver},
            { "Beer", Beer},
            { "Begonia", Begonia},
            { "Beige", Beige},
            { "Bdazzled Blue", BdazzledBlue},
            { "Big Dip Oruby", BigDipOruby},
            { "Big Foot Feet", BigFootFeet},
            { "Bisque", Bisque},
            { "Bistre", Bistre},
            { "Bistre Brown", BistreBrown},
            { "Bitter Lemon", BitterLemon},
            { "Bitter Lime", BitterLime},
            { "Bitter Sweet", Bittersweet},
            { "Bitter Sweet Shimmer", BittersweetShimmer},
            { "Black", Black},
            { "Black Bean", BlackBean},
            { "Black Chocolate", BlackChocolate},
            { "Black Coffee", BlackCoffee},
            { "Black Coral", BlackCoral},
            { "Black Leather Jacket", BlackLeatherJacket},
            { "Black Olive", BlackOlive},
            { "Blackberry", Blackberry},
            { "Black Shadows", BlackShadows},
            { "Blanched Almond", BlanchedAlmond},
            { "Blast Off Bronze", BlastOffBronze},
            { "Bleu De France", BleuDeFrance},
            { "Blizzard Blue", BlizzardBlue},
            { "Blond", Blond},
            { "Blood", Blood},
            { "Blood Orange", BloodOrange},
            { "Blood Red", BloodRed},
            { "Blood Animal", BloodAnimal},
            { "Blood Organ", BloodOrgan},
            { "Blue", Blue},
            { "Blue Crayola", BlueCrayola},
            { "Blue Munsell", BlueMunsell},
            { "Blue NCS", BlueNCS},
            { "Blue Pantone", BluePantone},
            { "Blue Pigment", BluePigment},
            { "Blue RYB", BlueRYB},
            { "Blue Bell", BlueBell},
            { "Blue Bolt", BlueBolt},
            { "Blue Cola", BlueCola},
            { "Blue Gray", BlueGray},
            { "Blue Green", BlueGreen},
            { "Blue Green ColWheel", BlueGreenColWheel},
            { "Blue Jeans", BlueJeans},
            { "Blue Lagoon", BlueLagoon},
            { "Blue Magenta Violet", BlueMagentaViolet},
            { "Blue Sapphire", BlueSapphire},
            { "Blue Violet", BlueViolet},
            { "Blue Violet Crayola", BlueVioletCrayola},
            { "Blue Violet ColWheel", BlueVioletColWheel},
            { "Blue Yonder", BlueYonder},
            { "Blueberry", Blueberry},
            { "Blue Bonnet", Bluebonnet},
            { "Blush", Blush},
            { "Bole", Bole},
            { "Bondi Blue", BondiBlue},
            { "Bone", Bone},
            { "Booger Buster", BoogerBuster},
            { "Boston University Red", BostonUniversityRed},
            { "Bottle Green", BottleGreen},
            { "Boysenberry", Boysenberry},
            { "Brandeis Blue", BrandeisBlue},
            { "Brandy", Brandy},
            { "Brass", Brass},
            { "BrickRed", BrickRed},
            { "Bright Cerulean", BrightCerulean},
            { "Bright Gray", BrightGray},
            { "Bright Green", BrightGreen},
            { "Bright Lavender", BrightLavender},
            { "Bright Lilac", BrightLilac},
            { "Bright Maroon", BrightMaroon},
            { "Bright Navy Blue", BrightNavyBlue},
            { "Bright Pink", BrightPink},
            { "Bright Turquoise", BrightTurquoise},
            { "Bright Ube", BrightUbe},
            { "Bright Yellow Crayola", BrightYellowCrayola},
            { "Brilliant Azure", BrilliantAzure},
            { "Brilliant Lavender", BrilliantLavender},
            { "Brilliant Rose", BrilliantRose},
            { "Brink Pink", BrinkPink},
            { "British Racing Green", BritishRacingGreen},
            { "Bronze", Bronze},
            { "Bronze Variant", BronzeVariant},
            { "Bronze Metallic", BronzeMetallic},
            { "Bronze Yellow", BronzeYellow},
            { "Brown", Brown},
            { "Brown Crayola", BrownCrayola},
            { "Brown Traditional", BrownTraditional},
            { "Brown Web", BrownWeb},
            { "Brown Nose", BrownNose},
            { "Brown Sugar", BrownSugar},
            { "Brown Chocolate", BrownChocolate},
            { "Brown Coffee", BrownCoffee},
            { "Brown Yellow", BrownYellow},
            { "Brunswick Green", BrunswickGreen},
            { "Bubble Gum", BubbleGum},
            { "Bubbles", Bubbles},
            { "Bud Green", BudGreen},
            { "Buff", Buff},
            { "Bulgarian Rose", BulgarianRose},
            { "Burgundy", Burgundy},
            { "Burlywood", Burlywood},
            { "Burnished Brown", BurnishedBrown},
            { "Burnt Orange", BurntOrange},
            { "Burnt Sienna", BurntSienna},
            { "Burnt Umber", BurntUmber},
            { "Button Blue", ButtonBlue},
            { "Byzantine", Byzantine},
            { "Byzantium", Byzantium},

            { "Cadet", Cadet},
            { "Cadet Blue", CadetBlue},
            { "Cadet Blue Crayola", CadetBlueCrayola},
            { "Cadet Grey", CadetGrey},
            { "Cadmium Blue", CadmiumBlue},
            { "Cadmium Green", CadmiumGreen},
            { "Cadmium Orange", CadmiumOrange},
            { "Cadmium Purple", CadmiumPurple},
            { "Cadmium Red", CadmiumRed},
            { "Cadmium Yellow", CadmiumYellow},
            { "Cadmium Violet", CadmiumViolet},
            { "Cafe Au Lait", CafeAuLait},
            { "Cafe Noir", CafeNoir},
            { "Cal Poly Green", CalPolyGreen},
            { "Calamansi", Calamansi},
            { "Cambridge Blue", CambridgeBlue},
            { "Camel", Camel},
            { "Cameo Pink", CameoPink},
            { "Camouflage Green", CamouflageGreen},
            { "Canary", Canary},
            { "Canary Yellow", CanaryYellow},
            { "Candy Apple Red", CandyAppleRed},
            { "Candy Pink", CandyPink},
            { "Capri", Capri},
            { "Caput Mortuum", CaputMortuum},
            { "Caramel", Caramel},
            { "Cardinal", Cardinal},
            { "Caribbean Green", CaribbeanGreen},
            { "Carmine", Carmine},
            { "Carmine MP", CarmineMP},
            { "Carmine Pink", CarminePink},
            { "Carmine Red", CarmineRed},
            { "Carnation Pink", CarnationPink},
            { "Carnelian", Carnelian},
            { "Carolina Blue", CarolinaBlue},
            { "Carrot Orange", CarrotOrange},
            { "Castleton Green", CastletonGreen},
            { "Catalina Blue", CatalinaBlue},
            { "Catawba", Catawba},
            { "Cedar Chest", CedarChest},
            { "Ceil", Ceil},
            { "Celadon", Celadon},
            { "Celadon Blue", CeladonBlue},
            { "Celadon Green", CeladonGreen},
            { "Celeste", Celeste},
            { "Celestial Blue", CelestialBlue},
            { "Celtic Blue", CelticBlue},
            { "Cerise", Cerise},
            { "Cerise Pink", CerisePink},
            { "Cerulean", Cerulean},
            { "Cerulean Blue", CeruleanBlue},
            { "Cerulean Frost", CeruleanFrost},
            { "Cerulean Crayola", CeruleanCrayola},
            { "CG Blue", CGBlue},
            { "CG Red", CGRed},
            { "Chamoisee", Chamoisee},
            { "Champagne", Champagne},
            { "Champagne Pink", ChampagnePink},
            { "Charcoal", Charcoal},
            { "Charleston Green", CharlestonGreen},
            { "Charm", Charm},
            { "Charm Pink", CharmPink},
            { "Chartreuse Traditional", ChartreuseTraditional},
            { "Chartreuse Web", ChartreuseWeb},
            { "Cheese", Cheese},
            { "Cherry", Cherry},
            { "Cherry Blossom Pink", CherryBlossomPink},
            { "Chestnut", Chestnut},
            { "China Pink", ChinaPink},
            { "China Rose", ChinaRose},
            { "Chinese Black", ChineseBlack},
            { "Chinese Blue", ChineseBlue},
            { "Chinese Bronze", ChineseBronze},
            { "Chinese Brown", ChineseBrown},
            { "Chinese Green", ChineseGreen},
            { "Chinese Gold", ChineseGold},
            { "Chinese Orange", ChineseOrange},
            { "Chinese Pink", ChinesePink},
            { "Chinese Purple", ChinesePurple},
            { "Chinese Red", ChineseRed},
            { "Chinese Red Variant", ChineseRedVariant},
            { "Chinese Silver", ChineseSilver},
            { "Chinese Violet", ChineseViolet},
            { "Chinese White", ChineseWhite},
            { "Chinese Yellow", ChineseYellow},
            { "Chlorophyll Green", ChlorophyllGreen},
            { "Chocolate Brown", ChocolateBrown},
            { "Chocolate Cosmos", ChocolateCosmos},
            { "Chocolate Kisses", ChocolateKisses},
            { "Chocolate Traditional", ChocolateTraditional},
            { "Chocolate Web", ChocolateWeb},
            { "Christmas Blue", ChristmasBlue},
            { "Christmas Blue Variant", ChristmasBlueVariant},
            { "Christmas Brown", ChristmasBrown},
            { "Christmas Brown Variant", ChristmasBrownVariant},
            { "Christmas Green", ChristmasGreen},
            { "Christmas Green Variant", ChristmasGreenVariant},
            { "Christmas Gold", ChristmasGold},
            { "Christmas Orange", ChristmasOrange},
            { "Christmas Orange Variant", ChristmasOrangeVariant},
            { "Christmas Pink", ChristmasPink},
            { "Christmas Pink Variant", ChristmasPinkVariant},
            { "Christmas Purple", ChristmasPurple},
            { "Christmas Purple Variant", ChristmasPurpleVariant},
            { "Christmas Red", ChristmasRed},
            { "Christmas Red Variant", ChristmasRedVariant},
            { "Christmas Silver", ChristmasSilver},
            { "Christmas Yellow", ChristmasYellow},
            { "Christmas Yellow Variant", ChristmasYellowVariant},
            { "Chrome Yellow", ChromeYellow},
            { "Cinereous", Cinereous},
            { "Cinnabar", Cinnabar},
            { "Cinnamon", Cinnamon},
            { "Cinnamon Satin", CinnamonSatin},
            { "Citrine", Citrine},
            { "Citrine Brown", CitrineBrown},
            { "Citron", Citron},
            { "Claret", Claret},
            { "Classic Rose", ClassicRose},
            { "Cobalt Blue", CobaltBlue},
            { "Cocoa Brown", CocoaBrown},
            { "Coconut", Coconut},
            { "Coffee", Coffee},
            { "Cola", Cola},
            { "Columbia Blue", ColumbiaBlue},
            { "Conditioner", Conditioner},
            { "Congo Pink", CongoPink},
            { "Cool Black", CoolBlack},
            { "Cool Grey", CoolGrey},
            { "Cookies and Cream", CookiesandCream},
            { "Copper", Copper},
            { "Copper Crayola", CopperCrayola},
            { "Copper Penny", CopperPenny},
            { "Copper Red", CopperRed},
            { "Copper Rose", CopperRose},
            { "Coquelicot", Coquelicot},
            { "Coral", Coral},
            { "Coral Pink", CoralPink},
            { "Coral Red", CoralRed},
            { "Coral Reef", CoralReef},
            { "Cordovan", Cordovan},
            { "Corn", Corn},
            { "Cornell Red", CornellRed},
            { "Cornflower Blue", CornflowerBlue},
            { "Cornflower", Cornflower},
            { "Cornsilk", Cornsilk},
            { "Cosmic Cobalt", CosmicCobalt},
            { "Cosmic Latte", CosmicLatte},
            { "Coyote Brown", CoyoteBrown},
            { "Cotton Candy", CottonCandy},
            { "Cream", Cream},
            { "Crimson", Crimson},
            { "Crimson Glory", CrimsonGlory},
            { "Crimson Red", CrimsonRed},
            { "Crystal", Crystal},
            { "Crystal Blue", CrystalBlue},
            { "Cultured", Cultured},
            { "Cyan", Cyan},
            { "Cyan Azure", CyanAzure},
            { "CyanBlue Azure", CyanBlueAzure},
            { "Cyan Cobal tBlue", CyanCobaltBlue},
            { "Cyan Cornflower Blue", CyanCornflowerBlue},
            { "Cyan Process", CyanProcess},
            { "Cyber Grape", CyberGrape},
            { "Cyber Yellow", CyberYellow},
            { "Cyclamen", Cyclamen},

            { "Daffodil", Daffodil},
            { "Dandelion", Dandelion},
            { "Dandelion Crayola", DandelionCrayola},
            { "DarkBlue", DarkBlue},
            { "Dark Blue Gray", DarkBlueGray},
            { "Dark Bronze", DarkBronze},
            { "Dark Bronze Coin", DarkBronzeCoin},
            { "Dark Brown", DarkBrown},
            { "Dark Brown Tangelo", DarkBrownTangelo},
            { "Dark Byzantium", DarkByzantium},
            { "Dark Candy Apple Red", DarkCandyAppleRed},
            { "Dark Cerulean", DarkCerulean},
            { "Dark Charcoal", DarkCharcoal},
            { "Dark Chestnut", DarkChestnut},
            { "Dark Chocolate", DarkChocolate},
            { "Dark Chocolate Hershey", DarkChocolateHershey},
            { "Dark Cornflower Blue", DarkCornflowerBlue},
            { "Dark Coral", DarkCoral},
            { "Dark Cyan", DarkCyan},
            { "Dark Electric Blue", DarkElectricBlue},
            { "Dark Gold", DarkGold},
            { "Dark Golden rod", DarkGoldenrod},
            { "Dark GrayX11", DarkGrayX11},
            { "Dark Green", DarkGreen},
            { "Dark GreenX11", DarkGreenX11},
            { "Dark Gunmetal", DarkGunmetal},
            { "Dark Imperial Blue", DarkImperialBlue},
            { "Dark Imperial Blue Variant", DarkImperialBlueVariant},
            { "Dark Jungle Green", DarkJungleGreen},
            { "Dark Khaki", DarkKhaki},
            { "Dark Lava", DarkLava},
            { "Dark Lavender", DarkLavender},
            { "Dark Lemon Lime", DarkLemonLime},
            { "Dark Liver", DarkLiver},
            { "Dark Liver Horses", DarkLiverHorses},
            { "Dark Magenta", DarkMagenta},
            { "Dark Medium Gray", DarkMediumGray},
            { "Dark Midnight Blue", DarkMidnightBlue},
            { "Dark Moss Green", DarkMossGreen},
            { "Dark Olive Green", DarkOliveGreen},
            { "Dark Orange", DarkOrange},
            { "Dark Orchid", DarkOrchid},
            { "Dark Pastel Blue", DarkPastelBlue},
            { "Dark Pastel Green", DarkPastelGreen},
            { "Dark Pastel Purple", DarkPastelPurple},
            { "Dark Pastel Red", DarkPastelRed},
            { "Dark Pink", DarkPink},
            { "Dark Powder Blue", DarkPowderBlue},
            { "Dark Puce", DarkPuce},
            { "Dark Purple", DarkPurple},
            { "Dark Raspberry", DarkRaspberry},
            { "Dark Red", DarkRed},
            { "Dark Salmon", DarkSalmon},
            { "Dark Scarlet", DarkScarlet},
            { "Dark Sea Green", DarkSeaGreen},
            { "Dark Sienna", DarkSienna},
            { "Dark Silver", DarkSilver},
            { "Dark Sky Blue", DarkSkyBlue},
            { "Dark Slate Blue", DarkSlateBlue},
            { "Dark Slate Gray", DarkSlateGray},
            { "Dark Spring Green", DarkSpringGreen},
            { "Dark Tan", DarkTan},
            { "Dark Tangerine", DarkTangerine},
            { "Dark Taupe", DarkTaupe},
            { "Dark Terra Cotta", DarkTerraCotta},
            { "Dark Turquoise", DarkTurquoise},
            { "Dark Vanilla", DarkVanilla},
            { "Dark Violet", DarkViolet},
            { "Dark Yellow", DarkYellow},
            { "Dartmouth Green", DartmouthGreen},
            { "Davys Grey", DavysGrey},
            { "Debian Red", DebianRed},
            { "Deep Amethyst", DeepAmethyst},
            { "Deep Aquamarine", DeepAquamarine},
            { "Deep Carmine", DeepCarmine},
            { "Deep Carmine Pink", DeepCarminePink},
            { "Deep Carrot Orange", DeepCarrotOrange},
            { "Deep Cerise", DeepCerise},
            { "Deep Champagne", DeepChampagne},
            { "Deep Chestnut", DeepChestnut},
            { "Deep Coffee", DeepCoffee},
            { "Deep Fuchsia", DeepFuchsia},
            { "Deep Green", DeepGreen},
            { "Deep Green Cyan Turquoise", DeepGreenCyanTurquoise},
            { "Deep Jungle Green", DeepJungleGreen},
            { "Deep Koamaru", DeepKoamaru},
            { "Deep Lemon", DeepLemon},
            { "Deep Lilac", DeepLilac},
            { "Deep Magenta", DeepMagenta},
            { "Deep Maroon", DeepMaroon},
            { "Deep Mauve", DeepMauve},
            { "Deep Moss Green", DeepMossGreen},
            { "Deep Peach", DeepPeach},
            { "Deep Pink", DeepPink},
            { "Deep Puce", DeepPuce},
            { "Deep Red", DeepRed},
            { "Deep Ruby", DeepRuby},
            { "Deep Saffron", DeepSaffron},
            { "Deep Sky Blue", DeepSkyBlue},
            { "DeepSpace Sparkle", DeepSpaceSparkle},
            { "Deep Spring Bud", DeepSpringBud},
            { "Deep Taupe", DeepTaupe},
            { "Deep Tuscan Red", DeepTuscanRed},
            { "Deep Violet", DeepViolet},
            { "Deer", Deer},
            { "Denim", Denim},
            { "Denim Blue", DenimBlue},
            { "Desaturated Cyan", DesaturatedCyan},
            { "Desert", Desert},
            { "Desert Sand", DesertSand},
            { "Desire", Desire},
            { "Diamond", Diamond},
            { "DimGray", DimGray},
            { "Dingy Gungeon", DingyGungeon},
            { "Dirt", Dirt},
            { "Dirt Brown", DirtBrown},
            { "Dirty White", DirtyWhite},
            { "Dodger Blue", DodgerBlue},
            { "Dodie Yellow", DodieYellow},
            { "Dogwood Rose", DogwoodRose},
            { "Dollar Bill", DollarBill},
            { "Dolphin Gray", DolphinGray},
            { "Drab", Drab},
            { "DukeBlue", DukeBlue},
            { "DustStorm", DustStorm},
            { "DutchWhite", DutchWhite},
            
            { "Earth Yellow", EarthYellow},
            { "Ebony", Ebony},
            { "Ecru", Ecru},
            { "Eerie Black", EerieBlack},
            { "Egg Plant", Eggplant},
            { "Egg Shell", Eggshell},
            { "Egyptian Blue", EgyptianBlue},
            { "Electric Blue", ElectricBlue},
            { "Electric Brown", ElectricBrown},
            { "Electric Crimson", ElectricCrimson},
            { "Electric Cyan", ElectricCyan},
            { "Electric Green", ElectricGreen},
            { "Electric Indigo", ElectricIndigo},
            { "Electric Lavender", ElectricLavender},
            { "Electric Lime", ElectricLime},
            { "Electric Orange", ElectricOrange},
            { "Electric Pink", ElectricPink},
            { "Electric Purple", ElectricPurple},
            { "Electric Red", ElectricRed},
            { "Electric Ultramarine", ElectricUltramarine},
            { "Electric Violet", ElectricViolet},
            { "Electric Yellow", ElectricYellow},
            { "Emerald", Emerald},
            { "Emerald Green", EmeraldGreen},
            { "Eminence", Eminence},
            { "English Green", EnglishGreen},
            { "English Lavender", EnglishLavender},
            { "EnglishRed", EnglishRed},
            { "English Vermillion", EnglishVermillion},
            { "English Violet", EnglishViolet},
            { "EtonBlue", EtonBlue},
            { "Eucalyptus", Eucalyptus},

            { "Fallow", Fallow},
            { "Falu Red", FaluRed},
            { "Fandango", Fandango},
            { "Fandango Pink", FandangoPink},
            { "Fashion Fuchsia", FashionFuchsia},
            { "Fawn", Fawn},
            { "Feldgrau", Feldgrau},
            { "Feldspar", Feldspar},
            { "Fern Green", FernGreen},
            { "Ferrari Red", FerrariRed},
            { "Field Drab", FieldDrab},
            { "Fiery Rose", FieryRose},
            { "Firebrick", Firebrick},
            { "Fire Engine Red", FireEngineRed},
            { "Fire Opal", FireOpal},
            { "Flame", Flame},
            { "Flamingo Pink", FlamingoPink},
            { "Flattery", Flattery},
            { "Flavescent", Flavescent},
            { "Flax", Flax},
            { "Flesh", Flesh},
            { "Flirt", Flirt},
            { "Floral White", FloralWhite},
            { "Fluorescent Blue", FluorescentBlue},
            { "Fluorescent Orange", FluorescentOrange},
            { "Fluorescent Pink", FluorescentPink},
            { "Fluorescent Yellow", FluorescentYellow},
            { "Folly", Folly},
            { "Forest Green Crayola", ForestGreenCrayola},
            { "Forest Green Traditional", ForestGreenTraditional},
            { "Forest Green Web", ForestGreenWeb},
            { "French Beige", FrenchBeige},
            { "French Bistre", FrenchBistre},
            { "French Blue", FrenchBlue},
            { "French Fuchsia", FrenchFuchsia},
            { "French Lilac", FrenchLilac},
            { "French Lime", FrenchLime},
            { "French Mauve", FrenchMauve},
            { "French Pink", FrenchPink},
            { "French Plum", FrenchPlum},
            { "French Puce", FrenchPuce},
            { "French Raspberry", FrenchRaspberry},
            { "French Rose", FrenchRose},
            { "French Sky Blue", FrenchSkyBlue},
            { "French Violet", FrenchViolet},
            { "French Wine", FrenchWine},
            { "Fresh Air", FreshAir},
            { "Frost bite", Frostbite},
            { "Fuchsia", Fuchsia},
            { "Fuchsia Crayola", FuchsiaCrayola},
            { "Fuchsia Pink", FuchsiaPink},
            { "Fuchsia Purple", FuchsiaPurple},
            { "Fuchsia Rose", FuchsiaRose},
            { "Fulvous", Fulvous},
            { "Fuzzy Wuzzy", FuzzyWuzzy},

            { "Gainsboro", Gainsboro},
            { "Gamboge", Gamboge},
            { "Gamboge Orange Brown", GambogeOrangeBrown},
            { "Garnet", Garnet},
            { "Gargoyle Gas", GargoyleGas},
            { "Generic Viridian", GenericViridian},
            { "Ghost White", GhostWhite},
            { "Giants Club", GiantsClub},
            { "Giants Orange", GiantsOrange},
            { "Glaucous", Glaucous},
            { "Glossy Grape", GlossyGrape},
            { "GO Green", GOGreen},
            { "Gold", Gold},
            { "Gold Metallic", GoldMetallic},
            { "Gold Web Golden", GoldWebGolden},
            { "Gold Crayola", GoldCrayola},
            { "Gold Fusion", GoldFusion},
            { "Gold Foil", GoldFoil},
            { "Golden Brown", GoldenBrown},
            { "Golden Poppy", GoldenPoppy},
            { "Golden Yellow", GoldenYellow},
            { "Goldenrod", Goldenrod},
            { "Granite Gray", GraniteGray},
            { "Granny Smith Apple", GrannySmithApple},
            { "Grape", Grape},
            { "Gray", Gray},
            { "Gray HTML CSS Gray", GrayHTMLCSSGray},
            { "Gray X11Gray", GrayX11Gray},
            { "Gray Asparagus", GrayAsparagus},
            { "Gray Blue", GrayBlue},
            { "Green", Green},
            { "Green ColWheel X11Green", GreenColWheelX11Green},
            { "Green Crayola", GreenCrayola},
            { "Green HTML CSS", GreenHTMLCSS},
            { "Green Munsell", GreenMunsell},
            { "Green NCS", GreenNCS},
            { "Green Pantone", GreenPantone},
            { "Green Pigment", GreenPigment},
            { "Green RYB", GreenRYB},
            { "Green Blue", GreenBlue},
            { "Green Cyan", GreenCyan},
            { "Green Lizard", GreenLizard},
            { "Green Sheen", GreenSheen},
            { "Green Yellow", GreenYellow},
            { "Grullo", Grullo},
            { "Guppie Green", GuppieGreen},
            { "Gunmetal", Gunmetal},

            { "HalayàÚbe", HalayàÚbe},
            { "Halloween Orange", HalloweenOrange},
            { "Han Blue", HanBlue},
            { "Han Purple", HanPurple},
            { "Hansa Yellow", HansaYellow},
            { "Harlequin", Harlequin},
            { "Harlequin Green", HarlequinGreen},
            { "Harvard Crimson", HarvardCrimson},
            { "Harvest Gold", HarvestGold},
            { "Heart Gold", HeartGold},
            { "Heat Wave", HeatWave},
            { "Heidelberg Red", HeidelbergRed},
            { "Heliotrope Gray", HeliotropeGray},
            { "Heliotrope Magenta", HeliotropeMagenta},
            { "Hollywood Cerise", HollywoodCerise},
            { "Honeydew", Honeydew},
            { "Honolulu Blue", HonoluluBlue},
            { "Hookers Green", HookersGreen},
            { "Hot Magenta", HotMagenta},
            { "Hot Pink", HotPink},
            { "Hunter Green", HunterGreen},

            { "Iceberg", Iceberg},
            { "Icterine", Icterine},
            { "Iguana Green", IguanaGreen},
            { "Illuminating Emerald", IlluminatingEmerald},
            { "Imperial", Imperial},
            { "Imperial Blue", ImperialBlue},
            { "Imperial Purple", ImperialPurple},
            { "Imperial Red", ImperialRed},
            { "Inchworm", Inchworm},
            { "Independence", Independence},
            { "India Green", IndiaGreen},
            { "Indian Red", IndianRed},
            { "Indian Yellow", IndianYellow},
            { "Indigo", Indigo},
            { "Indigo Dye", IndigoDye},
            { "Indigo Rainbow", IndigoRainbow},
            { "Indigo Web", IndigoWeb},
            { "Infra Red", InfraRed},
            { "Inter-dimensional Blue", InterdimensionalBlue},
            { "International Klein Blue", InternationalKleinBlue},
            { "International Orange Aerospace", InternationalOrangeAerospace},
            { "International Orange Engineering", InternationalOrangeEngineering},
            { "International Orange Golden Gate Bridge", InternationalOrangeGoldenGateBridge},
            { "Iris", Iris},
            { "Irresistible", Irresistible},
            { "Isabelline", Isabelline},
            { "Islamic Green", IslamicGreen},
            { "Italian Sky Blue", ItalianSkyBlue},
            { "Ivory", Ivory},

            { "Jacarta", Jacarta},
            { "Jacko Bean", JackoBean},
            { "Jade", Jade},
            { "Japanese Carmine", JapaneseCarmine},
            { "Japanese Indigo", JapaneseIndigo},
            { "Japanese Laurel", JapaneseLaurel},
            { "Japanese Violet", JapaneseViolet},
            { "Jasmine", Jasmine},
            { "Jasper", Jasper},
            { "Jasper Orange", JasperOrange},
            { "Jazzberry Jam", JazzberryJam},
            { "Jelly Bean", JellyBean},
            { "Jelly Bean Blue", JellyBeanBlue},
            { "Jet", Jet},
            { "Jet Stream", JetStream},
            { "Jonquil", Jonquil},
            { "Jordy Blue", JordyBlue},
            { "June Bud", JuneBud},
            { "Jungle Green", JungleGreen},

            { "Kelly Green", KellyGreen},
            { "Kenyan Copper", KenyanCopper},
            { "Keppel", Keppel},
            { "Key Lime", KeyLime},
            { "Khaki", Khaki},
            { "KhakiX11 Light Khaki", KhakiX11LightKhaki},
            { "Kiwi", Kiwi},
            { "Kobe", Kobe},
            { "Kobi", Kobi},
            { "Kobicha", Kobicha},
            { "Kombu Green", KombuGreen},
            { "KSU Purple", KSUPurple},

            { "LaSalle Green", LaSalleGreen},
            { "Languid Lavender", LanguidLavender},
            { "Lapis Lazuli", LapisLazuli},
            { "Laser Lemon", LaserLemon},
            { "Laurel Green", LaurelGreen},
            { "Lava", Lava},
            { "Lavender Floral", LavenderFloral},
            { "Lavender Web", LavenderWeb},
            { "Lavender Blue", LavenderBlue},
            { "Lavender Blush", LavenderBlush},
            { "Lavender Gray", LavenderGray},
            { "Lavender Indigo", LavenderIndigo},
            { "Lavender Magenta", LavenderMagenta},
            { "Lavender Mist", LavenderMist},
            { "Lavender Pink", LavenderPink},
            { "Lavender Purple", LavenderPurple},
            { "Lavender Rose", LavenderRose},
            { "Lawn Green", LawnGreen},
            { "Lemon", Lemon},
            { "Lemon Chiffon", LemonChiffon},
            { "Lemon Curry", LemonCurry},
            { "Lemon Glacier", LemonGlacier},
            { "Lemon Meringue", LemonMeringue},
            { "Lemon Yellow", LemonYellow},
            { "Lemon Yellow Crayola", LemonYellowCrayola},
            { "Lenurple", Lenurple},
            { "Liberty", Liberty},
            { "Licorice", Licorice},
            { "Light Apricot", LightApricot},
            { "Light Blue", LightBlue},
            { "Light Brown", LightBrown},
            { "Light Carmine Pink", LightCarminePink},
            { "Light Cobalt Blue", LightCobaltBlue},
            { "Light Coral", LightCoral},
            { "Light CornFlower Blue", LightCornFlowerBlue},
            { "Light Crimson", LightCrimson},
            { "Light Cyan", LightCyan},
            { "Light Deep Pink", LightDeepPink},
            { "Light French Beige", LightFrenchBeige},
            { "Light Fuchsia Pink", LightFuchsiaPink},
            { "Light Gold", LightGold},
            { "Light Goldenrod Yellow", LightGoldenrodYellow},
            { "Light Gray", LightGray},
            { "Light Grayish Magenta", LightGrayishMagenta},
            { "Light Green", LightGreen},
            { "Light Hot Pink", LightHotPink},
            { "Light Khaki", LightKhaki},
            { "Light Medium Orchid", LightMediumOrchid},
            { "Light Moss Green", LightMossGreen},
            { "Light Orange", LightOrange},
            { "Light Orchid", LightOrchid},
            { "Light Pastel Purple", LightPastelPurple},
            { "Light Periwinkle", LightPeriwinkle},
            { "Light Pink", LightPink},
            { "Light Red", LightRed},
            { "Light Red Ochre", LightRedOchre},
            { "Light Salmon", LightSalmon},
            { "Light Salmon Pink", LightSalmonPink},
            { "Light Sea Green", LightSeaGreen},
            { "Light Silver", LightSilver},
            { "Light Sky Blue", LightSkyBlue},
            { "Light Slate Gray", LightSlateGray},
            { "Light Steel Blue", LightSteelBlue},
            { "Light Taupe", LightTaupe},
            { "Light Thulian Pink", LightThulianPink},
            { "Light Yellow", LightYellow},
            { "Lilac", Lilac},
            { "Lilac Luster", LilacLuster},
            { "Lime ColWheel", LimeColWheel},
            { "Lime WebX11 Green", LimeWebX11Green},
            { "Lime Green", LimeGreen},
            { "Limerick", Limerick},
            { "Lincoln Green", LincolnGreen},
            { "Linen", Linen},
            { "Lion", Lion},
            { "Liseran Purple", LiseranPurple},
            { "Little Boy Blue", LittleBoyBlue},
            { "Little Girl Pink", LittleGirlPink},
            { "Liver", Liver},
            { "Liver Dogs", LiverDogs},
            { "Liver Organ", LiverOrgan},
            { "Liver Chestnut", LiverChestnut},
            { "Livid", Livid},
            { "Lotion", Lotion},
            { "Lumber", Lumber},
            { "Lust", Lust},

            { "Maastricht Blue", MaastrichtBlue},
            { "Macaroniand Cheese", MacaroniandCheese},
            { "Madder Lake", MadderLake},
            { "Magenta", Magenta},
            { "Magenta Crayola", MagentaCrayola},
            { "Magenta Dye", MagentaDye},
            { "Magenta Pantone", MagentaPantone},
            { "Magenta Process", MagentaProcess},
            { "Magenta Haze", MagentaHaze},
            { "Magenta Pink", MagentaPink},
            { "Magic Mint", MagicMint},
            { "Magic Potion", MagicPotion},
            { "Magnolia", Magnolia},
            { "Mahogany", Mahogany},
            { "Maize", Maize},
            { "Maize Crayola", MaizeCrayola},
            { "Majorelle Blue", MajorelleBlue},
            { "Malachite", Malachite},
            { "Manatee", Manatee},
            { "Mandarin", Mandarin},
            { "Mango Green", MangoGreen},
            { "Mango Tango", MangoTango},
            { "Mantis", Mantis},
            { "Mardi Gras", MardiGras},
            { "Marigold", Marigold},
            { "Maroon Crayola", MaroonCrayola},
            { "Maroon HTML CSS", MaroonHTMLCSS},
            { "MaroonX11", MaroonX11},
            { "Mauve", Mauve},
            { "Mauve Taupe", MauveTaupe},
            { "Mauvelous", Mauvelous},
            { "Maximum Blue", MaximumBlue},
            { "Maximum Blue Green", MaximumBlueGreen},
            { "Maximum Blue Purple", MaximumBluePurple},
            { "Maximum Green", MaximumGreen},
            { "Maximum Green Yellow", MaximumGreenYellow},
            { "Maximum Purple", MaximumPurple},
            { "Maximum Red", MaximumRed},
            { "Maximum Red Purple", MaximumRedPurple},
            { "Maximum Yellow", MaximumYellow},
            { "Maximum Yellow Red", MaximumYellowRed},
            { "MayGreen", MayGreen},
            { "MayaBlue", MayaBlue},
            { "MeatBrown", MeatBrown},
            { "Medium Aquamarine", MediumAquamarine},
            { "Medium Blue", MediumBlue},
            { "Medium Candy Apple Red", MediumCandyAppleRed},
            { "Medium Carmine", MediumCarmine},
            { "Medium Champagne", MediumChampagne},
            { "Medium Electric Blue", MediumElectricBlue},
            { "Medium Jungle Green", MediumJungleGreen},
            { "Medium Lavender Magenta", MediumLavenderMagenta},
            { "Medium Orchid", MediumOrchid},
            { "Medium Persian Blue", MediumPersianBlue},
            { "Medium Purple", MediumPurple},
            { "Medium Red Violet", MediumRedViolet},
            { "Medium Ruby", MediumRuby},
            { "Medium Sea Green", MediumSeaGreen},
            { "Medium Sky Blue", MediumSkyBlue},
            { "Medium Slate Blue", MediumSlateBlue},
            { "Medium Spring Bud", MediumSpringBud},
            { "Medium Spring Green", MediumSpringGreen},
            { "Medium Taupe", MediumTaupe},
            { "Medium Turquoise", MediumTurquoise},
            { "Medium Tuscan Red", MediumTuscanRed},
            { "Medium Vermilion", MediumVermilion},
            { "Medium Violet Red", MediumVioletRed},
            { "Mellow Apricot", MellowApricot},
            { "Mellow Yellow", MellowYellow},
            { "Melon", Melon},
            { "Menthol", Menthol},
            { "Metallic Blue", MetallicBlue},
            { "Metallic Bronze", MetallicBronze},
            { "Metallic Brown", MetallicBrown},
            { "Metallic Gold", MetallicGold},
            { "Metallic Green", MetallicGreen},
            { "Metallic Orange", MetallicOrange},
            { "Metallic Pink", MetallicPink},
            { "Metallic Red", MetallicRed},
            { "Metallic Seaweed", MetallicSeaweed},
            { "Metallic Silver", MetallicSilver},
            { "Metallic Sunburst", MetallicSunburst},
            { "Metallic Violet", MetallicViolet},
            { "Metallic Yellow", MetallicYellow},
            { "Mexican Pink", MexicanPink},
            { "Middle Blue", MiddleBlue},
            { "Middle Blue Green", MiddleBlueGreen},
            { "Middle Blue Purple", MiddleBluePurple},
            { "Middle Grey", MiddleGrey},
            { "Middle Green", MiddleGreen},
            { "Middle Green Yellow", MiddleGreenYellow},
            { "Middle Purple", MiddlePurple},
            { "Middle Red", MiddleRed},
            { "Middle Red Purple", MiddleRedPurple},
            { "Middle Yellow", MiddleYellow},
            { "Middle Yellow Red", MiddleYellowRed},
            { "Midnight", Midnight},
            { "Midnight Blue", MidnightBlue},
            { "Midnight Blue Variant", MidnightBlueVariant},
            { "Midnight Green Eagle Green", MidnightGreenEagleGreen},
            { "Mikado Yellow", MikadoYellow},
            { "Milk", Milk},
            { "Milk Chocolate", MilkChocolate},
            { "Mimi Pink", MimiPink},
            { "Mindaro", Mindaro},
            { "Ming", Ming},
            { "Minion Yellow", MinionYellow},
            { "Mint", Mint},
            { "Mint Cream", MintCream},
            { "Mint Green", MintGreen},
            { "Misty Moss", MistyMoss},
            { "Misty Rose", MistyRose},
            { "Moccasin", Moccasin},
            { "Mocha", Mocha},
            { "Mode Beige", ModeBeige},
            { "Moonstone", Moonstone},
            { "Moonstone Blue", MoonstoneBlue},
            { "Mordant Red19", MordantRed19},
            { "Morning Blue", MorningBlue},
            { "Moss Green", MossGreen},
            { "Mountain Meadow", MountainMeadow},
            { "Mountbatten Pink", MountbattenPink},
            { "MSU Green", MSUGreen},
            { "Mud", Mud},
            { "Mughal Green", MughalGreen},
            { "Mulberry", Mulberry},
            { "Mulberry Crayola", MulberryCrayola},
            { "Mummy Tomb", MummyTomb},
            { "Mustard", Mustard},
            { "Mustard Brown", MustardBrown},
            { "Mustard Green", MustardGreen},
            { "Mustard Yellow", MustardYellow},
            { "Myrtle Green", MyrtleGreen},
            { "Mystic", Mystic},
            { "Mystic Maroon", MysticMaroon},
            { "Mystic Red", MysticRed},

            { "Naples Yellow", NaplesYellow},
            { "Navajo White", NavajoWhite},
            { "Navy Blue", NavyBlue},
            { "Navy Blue Crayola", NavyBlueCrayola},
            { "Neon Blue", NeonBlue},
            { "Neon Green", NeonGreen},
            { "New Car", NewCar},
            { "New York Pink", NewYorkPink},
            { "Nickel", Nickel},
            { "Non-Photo Blue", NonPhotoBlue},
            { "North Texas Green", NorthTexasGreen},
            { "Nyanza", Nyanza},

            { "Ocean Blue", OceanBlue},
            { "Ocean Boat Blue", OceanBoatBlue},
            { "Ocean Green", OceanGreen},
            { "Ochre", Ochre},
            { "Office Green", OfficeGreen},
            { "Ogre Odor", OgreOdor},
            { "Old Burgundy", OldBurgundy},
            { "Old Gold", OldGold},
            { "Old Heliotrope", OldHeliotrope},
            { "Old Lace", OldLace},
            { "Old Lavender", OldLavender},
            { "Old Mauve", OldMauve},
            { "Old MossGreen", OldMossGreen},
            { "Old Rose", OldRose},
            { "Old Silver", OldSilver},
            { "Olive", Olive},
            { "Olive Drab", OliveDrab},
            { "Olive Drab Variant", OliveDrabVariant},
            { "Olive Green", OliveGreen},
            { "Olivine", Olivine},
            { "Onyx", Onyx},
            { "Opal", Opal},
            { "Opera Mauve", OperaMauve},
            { "Orange", Orange},
            { "Orange ColWheel", OrangeColWheel},
            { "Orange Crayola", OrangeCrayola},
            { "Orange Pantone", OrangePantone},
            { "Orange RYB", OrangeRYB},
            { "Orange Web", OrangeWeb},
            { "Orange Peel", OrangePeel},
            { "Orange Red", OrangeRed},
            { "Orange Red Crayola", OrangeRedCrayola},
            { "Orange Soda", OrangeSoda},
            { "Orange Yellow", OrangeYellow},
            { "Orange Yellow Crayola", OrangeYellowCrayola},
            { "Orchid", Orchid},
            { "Orchid Pink", OrchidPink},
            { "Orchid Crayola", OrchidCrayola},
            { "Orioles Orange", OriolesOrange},
            { "Otter Brown", OtterBrown},
            { "Outer Space", OuterSpace},
            { "Outer Space Crayola", OuterSpaceCrayola},
            { "Outrageous Orange", OutrageousOrange},
            { "Oxblood", Oxblood},
            { "Oxford Blue", OxfordBlue},
            { "Oxley", Oxley},
            { "OU Crimson Red", OUCrimsonRed},

            { "Pacific Blue", PacificBlue},
            { "Pakistan Green", PakistanGreen},
            { "Palatinate Blue", PalatinateBlue},
            { "Palatinate Purple", PalatinatePurple},
            { "Pale Aqua", PaleAqua},
            { "Pale Blue", PaleBlue},
            { "Pale Brown", PaleBrown},
            { "Pale Carmine", PaleCarmine},
            { "Pale Cerulean", PaleCerulean},
            { "Pale Chestnut", PaleChestnut},
            { "Pale Copper", PaleCopper},
            { "Pale CornFlower Blue", PaleCornFlowerBlue},
            { "Pale Cyan", PaleCyan},
            { "Pale Gold", PaleGold},
            { "Pale Goldenrod", PaleGoldenrod},
            { "Pale Green", PaleGreen},
            { "Pale Lavender", PaleLavender},
            { "Pale Magenta", PaleMagenta},
            { "Pale Magenta Pink", PaleMagentaPink},
            { "Pale Pink", PalePink},
            { "Pale Plum", PalePlum},
            { "Pale Red Violet", PaleRedViolet},
            { "Pale Robin Egg Blue", PaleRobinEggBlue},
            { "Pale Silver", PaleSilver},
            { "Pale Spring Bud", PaleSpringBud},
            { "Pale Taupe", PaleTaupe},
            { "Pale Turquoise", PaleTurquoise},
            { "Pale Violet", PaleViolet},
            { "Pale Violet Red", PaleVioletRed},
            { "Palm Leaf", PalmLeaf},
            { "Pansy Purple", PansyPurple},
            { "Paolo Veronese Green", PaoloVeroneseGreen},
            { "Papaya Whip", PapayaWhip},
            { "Paradise Pink", ParadisePink},
            { "Paris Green", ParisGreen},
            { "Parrot Pink", ParrotPink},
            { "Pastel Blue", PastelBlue},
            { "Pastel Brown", PastelBrown},
            { "Pastel Gray", PastelGray},
            { "Pastel Green", PastelGreen},
            { "Pastel Magenta", PastelMagenta},
            { "Pastel Orange", PastelOrange},
            { "Pastel Pink", PastelPink},
            { "Pastel Purple", PastelPurple},
            { "Pastel Red", PastelRed},
            { "Pastel Violet", PastelViolet},
            { "Pastel Yellow", PastelYellow},
            { "Patriarch", Patriarch},
            { "Payne Grey", PayneGrey},
            { "Peach", Peach},
            { "Peach Variant", PeachVariant},
            { "Peach Orange", PeachOrange},
            { "Peach Puff", PeachPuff},
            { "Peach Yellow", PeachYellow},
            { "Pear", Pear},
            { "Pearl", Pearl},
            { "Pearl Aqua", PearlAqua},
            { "Pearly Purple", PearlyPurple},
            { "Peridot", Peridot},
            { "Periwinkle", Periwinkle},
            { "Periwinkle Crayola", PeriwinkleCrayola},
            { "Permanent GeraLake", PermanentGeraLake},
            { "Persian Blue", PersianBlue},
            { "Persian Green", PersianGreen},
            { "Persian Indigo", PersianIndigo},
            { "Persian Orange", PersianOrange},
            { "Persian Pink", PersianPink},
            { "Persian Plum", PersianPlum},
            { "Persian Red", PersianRed},
            { "Persian Rose", PersianRose},
            { "Persimmon", Persimmon},
            { "Peru", Peru},
            { "Pewter Blue", PewterBlue},
            { "Phillipine Blue", PhillipineBlue},
            { "Phillipine Bronze", PhillipineBronze},
            { "Phillipine Brown", PhillipineBrown},
            { "Phillipine Gold", PhillipineGold},
            { "Phillipine Golden Yellow", PhillipineGoldenYellow},
            { "Phillipine Gray", PhillipineGray},
            { "Phillipine Green", PhillipineGreen},
            { "Phillipine Orange", PhillipineOrange},
            { "Phillipine Pink", PhillipinePink},
            { "Phillipine Red", PhillipineRed},
            { "Phillipine Silver", PhillipineSilver},
            { "Phillipine Violet", PhillipineViolet},
            { "Phillipine Yellow", PhillipineYellow},
            { "Phlox", Phlox},
            { "Phthalo Blue", PhthaloBlue},
            { "Phthalo Green", PhthaloGreen},
            { "Pictorial Carmine", PictorialCarmine},
            { "Piggy Pink", PiggyPink},
            { "Pine Green", PineGreen},
            { "Pine Tree", PineTree},
            { "Pineapple", Pineapple},
            { "Pink", Pink},
            { "Pink Pantone", PinkPantone},
            { "Pink Flamingo", PinkFlamingo},
            { "Pink Lace", PinkLace},
            { "Pink Lavender", PinkLavender},
            { "Pink Orange", PinkOrange},
            { "Pink Pearl", PinkPearl},
            { "Pink Raspberry", PinkRaspberry},
            { "Pink Sherbet", PinkSherbet},
            { "Pistachio", Pistachio},
            { "Pixie Powder", PixiePowder},
            { "Platinum", Platinum},
            { "Plum", Plum},
            { "Plum Web", PlumWeb},
            { "Plump Purple", PlumpPurple},
            { "Police Blue", PoliceBlue},
            { "Polished Pine", PolishedPine},
            { "Pompand Power", PompandPower},
            { "Popstar", Popstar},
            { "Portland Orange", PortlandOrange},
            { "Powder Blue", PowderBlue},
            { "Princess Perfume", PrincessPerfume},
            { "Princeton Orange", PrincetonOrange},
            { "Prune", Prune},
            { "Prussian Blue", PrussianBlue},
            { "Psychedelic Purple", PsychedelicPurple},
            { "Puce", Puce},
            { "PuceRed", PuceRed},
            { "Pullman Brown UPS Brown", PullmanBrownUPSBrown},
            { "Pullman Green", PullmanGreen},
            { "Pumpkin", Pumpkin},
            { "Purple HTML", PurpleHTML},
            { "Purple Munsell", PurpleMunsell},
            { "PurpleX11", PurpleX11},
            { "Purple Heart", PurpleHeart},
            { "Purple Mountain Majesty", PurpleMountainMajesty},
            { "Purple Navy", PurpleNavy},
            { "Purple Pizzazz", PurplePizzazz},
            { "Purple Plum", PurplePlum},
            { "Purple Taupe", PurpleTaupe},
            { "Purpureus", Purpureus},

            { "Quartz", Quartz},
            { "Queen Blue", QueenBlue},
            { "Queen Pink", QueenPink},
            { "Quick Silver", QuickSilver},
            { "Quinacridone Magenta", QuinacridoneMagenta},
            { "Quincy", Quincy},

            { "Rackley", Rackley},
            { "Radical Red", RadicalRed},
            { "Raisin Black", RaisinBlack},
            { "Rajah", Rajah},
            { "Raspberry", Raspberry},
            { "Raspberry Glace", RaspberryGlace},
            { "Raspberry Pink", RaspberryPink},
            { "Raspberry Rose", RaspberryRose},
            { "RawSienna", RawSienna},
            { "RawUmber", RawUmber},
            { "RazzleDazzle Rose", RazzleDazzleRose},
            { "Razzmatazz", Razzmatazz},
            { "Razzmic Berry", RazzmicBerry},
            { "Rebecca Purple", RebeccaPurple},
            { "Red", Red},
            { "Red Crayola", RedCrayola},
            { "Red Munsell", RedMunsell},
            { "Red NCS", RedNCS},
            { "Red Pantone", RedPantone},
            { "Red Pigment", RedPigment},
            { "Red RYB", RedRYB},
            { "Red Brown", RedBrown},
            { "Red Devil", RedDevil},
            { "Red Orange", RedOrange},
            { "Red Orange Crayola", RedOrangeCrayola},
            { "Red Orange ColWheel", RedOrangeColWheel},
            { "Red Purple", RedPurple},
            { "Red Salsa", RedSalsa},
            { "Red Violet", RedViolet},
            { "Red Violet Crayola", RedVioletCrayola},
            { "Red Violet ColWheel", RedVioletColWheel},
            { "Redwood", Redwood},
            { "Regalia", Regalia},
            { "Registration Black", RegistrationBlack},
            { "Resolution Blue", ResolutionBlue},
            { "Rhythm", Rhythm},
            { "Rich Black", RichBlack},
            { "Rich Black FOGRA29", RichBlackFOGRA29},
            { "Rich Black FOGRA39", RichBlackFOGRA39},
            { "Rich Brilliant Lavender", RichBrilliantLavender},
            { "Rich Carmine", RichCarmine},
            { "Rich Electric Blue", RichElectricBlue},
            { "Rich Lavender", RichLavender},
            { "Rich Lilac", RichLilac},
            { "Rich Maroon", RichMaroon},
            { "Rifle Green", RifleGreen},
            { "Ripe Mango", RipeMango},
            { "Roast Coffee", RoastCoffee},
            { "Robin Egg Blue", RobinEggBlue},
            { "Rocket Metallic", RocketMetallic},
            { "Roman Silver", RomanSilver},
            { "Root Beer", RootBeer},
            { "Rose", Rose},
            { "Rose Bonbon", RoseBonbon},
            { "Rose Dust", RoseDust},
            { "Rose Ebony", RoseEbony},
            { "Rose Garnet", RoseGarnet},
            { "Rose Gold", RoseGold},
            { "Rose Madder", RoseMadder},
            { "Rose Pink", RosePink},
            { "Rose Quartz", RoseQuartz},
            { "Rose Red", RoseRed},
            { "Rose Taupe", RoseTaupe},
            { "Rose Vale", RoseVale},
            { "Rosewood", Rosewood},
            { "Rosso Corsa", RossoCorsa},
            { "Rosy Brown", RosyBrown},
            { "Royal Azure", RoyalAzure},
            { "Royal Blue", RoyalBlue},
            { "Royal Blue Variant", RoyalBlueVariant},
            { "Royal Brown", RoyalBrown},
            { "Royal Fuchsia", RoyalFuchsia},
            { "Royal Green", RoyalGreen},
            { "Royal Orange", RoyalOrange},
            { "Royal Pink", RoyalPink},
            { "Royal Red", RoyalRed},
            { "Royal Red Variant", RoyalRedVariant},
            { "Royal Purple", RoyalPurple},
            { "Royal Yellow", RoyalYellow},
            { "Ruber", Ruber},
            { "Rubine Red", RubineRed},
            { "Ruby", Ruby},
            { "Ruby Red", RubyRed},
            { "Ruddy", Ruddy},
            { "Ruddy Brown", RuddyBrown},
            { "Ruddy Pink", RuddyPink},
            { "Rufous", Rufous},
            { "Russet", Russet},
            { "Russian Green", RussianGreen},
            { "Russian Violet", RussianViolet},
            { "Rust", Rust},
            { "Rusty Red", RustyRed},

            { "Sacramento State Green", SacramentoStateGreen},
            { "Saddle Brown", SaddleBrown},
            { "Safety Orange", SafetyOrange},
            { "Safety Orange Blaze Orange", SafetyOrangeBlazeOrange},
            { "Safety Yellow", SafetyYellow},
            { "Saffron", Saffron},
            { "Sage", Sage},
            { "St Patrick Blue", StPatrickBlue},
            { "Salem", Salem},
            { "Salmon", Salmon},
            { "Sand", Sand},
            { "Sand Dune", SandDune},
            { "Sandstorm", Sandstorm},
            { "Sandy Brown", SandyBrown},
            { "Sandy Tan", SandyTan},
            { "Sandy Taupe", SandyTaupe},
            { "Sangria", Sangria},
            { "Sap Green", SapGreen},
            { "Sapphire", Sapphire},
            { "Sapphire Blue", SapphireBlue},
            { "Sasquatch Socks", SasquatchSocks},
            { "Satin Sheen Gold", SatinSheenGold},
            { "Scarlet", Scarlet},
            { "Scarlet Variant", ScarletVariant},
            { "Schauss Pink", SchaussPink},
            { "School Bus Yellow", SchoolBusYellow},
            { "Screamin Green", ScreaminGreen},
            { "Sea Blue", SeaBlue},
            { "Sea Foam Green", SeaFoamGreen},
            { "Sea Green", SeaGreen},
            { "Sea Green Crayola", SeaGreenCrayola},
            { "Sea Serpent", SeaSerpent},
            { "Seal Brown", SealBrown},
            { "Sea shell", Seashell},
            { "Selective Yellow", SelectiveYellow},
            { "Sepia", Sepia},
            { "Shadow", Shadow},
            { "Shadow Blue", ShadowBlue},
            { "Shampoo", Shampoo},
            { "Shamrock Green", ShamrockGreen},
            { "Shandy", Shandy},
            { "Sheen Green", SheenGreen},
            { "Shimmering Blush", ShimmeringBlush},
            { "Shinny Shamrock", ShinnyShamrock},
            { "Shocking Pink", ShockingPink},
            { "Shocking Pink Crayola", ShockingPinkCrayola},
            { "Sienna", Sienna},
            { "Silver", Silver},
            { "Silver Crayola", SilverCrayola},
            { "Silver Metallic", SilverMetallic},
            { "Silver Chalice", SilverChalice},
            { "Silver Foil", SilverFoil},
            { "Silver Lake Blue", SilverLakeBlue},
            { "Silver Pink", SilverPink},
            { "Silver Sand", SilverSand},
            { "Sinopia", Sinopia},
            { "Sizzling Red", SizzlingRed},
            { "Sizzling Sunrise", SizzlingSunrise},
            { "Skobeloff", Skobeloff},
            { "Sky Blue", SkyBlue},
            { "Sky Blue Crayola", SkyBlueCrayola},
            { "Sky Magenta", SkyMagenta},
            { "Slate Blue", SlateBlue},
            { "Slate Gray", SlateGray},
            { "Slimmy Green", SlimmyGreen},
            { "Smalt Dark Powder Blue", SmaltDarkPowderBlue},
            { "Smashed Pumpkin", SmashedPumpkin},
            { "Smitten", Smitten},
            { "Smoke", Smoke},
            { "Smokey Topaz", SmokeyTopaz},
            { "Smoky Black", SmokyBlack},
            { "Smoky Topaz", SmokyTopaz},
            { "Snow", Snow},
            { "Soap", Soap},
            { "Soldier Green", SoldierGreen},
            { "Sonic Silver", SonicSilver},
            { "Spartan Crimson", SpartanCrimson},
            { "Space Cadet", SpaceCadet},
            { "Spanish Bistre", SpanishBistre},
            { "Spanish Blue", SpanishBlue},
            { "Spanish Carmine", SpanishCarmine},
            { "Spanish Crimson", SpanishCrimson},
            { "Spanish Gray", SpanishGray},
            { "Spanish Green", SpanishGreen},
            { "Spanish Orange", SpanishOrange},
            { "Spanish Pink", SpanishPink},
            { "Spanish Purple", SpanishPurple},
            { "Spanish Red", SpanishRed},
            { "Spanish Sky Blue", SpanishSkyBlue},
            { "Spanish Violet", SpanishViolet},
            { "Spanish Viridian", SpanishViridian},
            { "Spanish Yellow", SpanishYellow},
            { "SpicyMix", SpicyMix},
            { "Spiro Disco Ball", SpiroDiscoBall},
            { "Spring Bud", SpringBud},
            { "Spring Frost", SpringFrost},
            { "Spring Green", SpringGreen},
            { "Spring Crayola", SpringCrayola},
            { "Star Command Blue", StarCommandBlue},
            { "Steel Blue", SteelBlue},
            { "Steel Pink", SteelPink},
            { "Steel Teal", SteelTeal},
            { "Stil De Grain Yellow", StilDeGrainYellow},
            { "Stizza", Stizza},
            { "Stormcloud", Stormcloud},
            { "Straw", Straw},
            { "Strawberry", Strawberry},
            { "Sugar Plum", SugarPlum},
            { "Sunburnt Cyclops", SunburntCyclops},
            { "Sunglow", Sunglow},
            { "Sunny", Sunny},
            { "Sunray", Sunray},
            { "Sunset", Sunset},
            { "Sunset Orange", SunsetOrange},
            { "Super Pink", SuperPink},
            { "Sweet Brown", SweetBrown},

            { "Tan", Tan},
            { "Tan Crayola", TanCrayola},
            { "Tangelo", Tangelo},
            { "Tangerine", Tangerine},
            { "Tangerine Yellow", TangerineYellow},
            { "Tango Pink", TangoPink},
            { "Tart Orange", TartOrange},
            { "Taupe", Taupe},
            { "Taupe Gray", TaupeGray},
            { "Tea Green", TeaGreen},
            { "Tea Rose", TeaRose},
            { "Tea Rose Variant", TeaRoseVariant},
            { "Teal", Teal},
            { "Teal Blue", TealBlue},
            { "Teal Deer", TealDeer},
            { "Teal Green", TealGreen},
            { "Telemagenta", Telemagenta},
            { "Temptress", Temptress},
            { "Tenné", Tenné},
            { "Terra Cotta", TerraCotta},
            { "Thistle", Thistle},
            { "Thistle Crayola", ThistleCrayola},
            { "Thulian Pink", ThulianPink},
            { "Tickle Me Pink", TickleMePink},
            { "Tiffany Blue", TiffanyBlue},
            { "Tiger Eye", TigerEye},
            { "Timberwolf", Timberwolf},
            { "Titanium", Titanium},
            { "Titanium Yellow", TitaniumYellow},
            { "Tomato", Tomato},
            { "Toolbox", Toolbox},
            { "Topaz", Topaz},
            { "Tractor Red", TractorRed},
            { "Trolley Grey", TrolleyGrey},
            { "Tropical Rainforest", TropicalRainforest},
            { "Tropical Violet", TropicalViolet},
            { "True Blue", TrueBlue},
            { "Tufts Blue", TuftsBlue},
            { "Tulip", Tulip},
            { "Tumbleweed", Tumbleweed},
            { "Turkish Rose", TurkishRose},
            { "Turquoise", Turquoise},
            { "Turquoise Blue", TurquoiseBlue},
            { "Turquoise Green", TurquoiseGreen},
            { "Turquoise Surf", TurquoiseSurf},
            { "Turtle Green", TurtleGreen},
            { "Tuscan", Tuscan},
            { "Tuscan Brown", TuscanBrown},
            { "Tuscan Red", TuscanRed},
            { "Tuscan Tan", TuscanTan},
            { "Tuscany", Tuscany},
            { "Twilight Lavender", TwilightLavender},
            { "Tyrian Purple", TyrianPurple},

            { "UA Blue", UABlue},
            { "UA Red", UARed},
            { "Ube", Ube},
            { "UCLA Blue", UCLABlue},
            { "UCLA Gold", UCLAGold},
            { "UE Red", UERed},
            { "UFO Green", UFOGreen},
            { "Ultramarine", Ultramarine},
            { "Ultramarine Blue", UltramarineBlue},
            { "Ultra Pink", UltraPink},
            { "Ultra Red", UltraRed},
            { "Umber", Umber},
            { "Unbleached Silk", UnbleachedSilk},
            { "United Nations Blue", UnitedNationsBlue},
            { "University Of California Gold", UniversityOfCaliforniaGold},
            { "University Of Tenessee Orange", UniversityOfTenesseeOrange},
            { "Unmellow Yellow", UnmellowYellow},
            { "UP Forest Green", UPForestGreen},
            { "UP Maroon", UPMaroon},
            { "Upsdell Red", UpsdellRed},
            { "Urobilin", Urobilin},
            { "USAFA Blue", USAFABlue},
            { "USC Cardinal", USCCardinal},
            { "USC Gold", USCGold},
            { "Utah Crimson", UtahCrimson},

            { "Vampire Black", VampireBlack},
            { "VanDyke Brown", VanDykeBrown},
            { "Vanilla", Vanilla},
            { "Vanilla Ice", VanillaIce},
            { "Vegas Gold", VegasGold},
            { "Venetian Red", VenetianRed},
            { "Verdigris", Verdigris},
            { "Vermilion", Vermilion},
            { "Vermilion Variant", VermilionVariant},
            { "Veronica", Veronica},
            { "Verse Green", VerseGreen},
            { "Very Light Azure", VeryLightAzure},
            { "Very Light Blue", VeryLightBlue},
            { "VeryLight Malachite Green", VeryLightMalachiteGreen},
            { "Very Light Tangelo", VeryLightTangelo},
            { "VeryPale Orange", VeryPaleOrange},
            { "VeryPale Yellow", VeryPaleYellow},
            { "Violet", Violet},
            { "Violet ColWheel", VioletColWheel},
            { "Violet Crayola", VioletCrayola},
            { "Violet RYB", VioletRYB},
            { "Violet Web", VioletWeb},
            { "Violet Blue", VioletBlue},
            { "Violet Blue Crayola", VioletBlueCrayola},
            { "Violet Red", VioletRed},
            { "Violet Red Variant", VioletRedVariant},
            { "Violin Brown", ViolinBrown},
            { "Viridian", Viridian},
            { "Viridian Green", ViridianGreen},
            { "Vista Blue", VistaBlue},
            { "Vivid Amber", VividAmber},
            { "Vivid Auburn", VividAuburn},
            { "Vivid Burgundy", VividBurgundy},
            { "Vivid Cerise", VividCerise},
            { "Vivid Cerulean", VividCerulean},
            { "Vivid Crimson", VividCrimson},
            { "Vivid Gamboge", VividGamboge},
            { "Vivid Lime Green", VividLimeGreen},
            { "Vivid Malachite", VividMalachite},
            { "Vivid Mulberry", VividMulberry},
            { "Vivid Orange", VividOrange},
            { "Vivid Orange Peel", VividOrangePeel},
            { "Vivid Orchid", VividOrchid},
            { "Vivid Red", VividRed},
            { "Vivid Red Tangelo", VividRedTangelo},
            { "Vivid Sky Blue", VividSkyBlue},
            { "Vivid Tangelo", VividTangelo},
            { "Vivid Tangerine", VividTangerine},
            { "Vivid Vermilion", VividVermilion},
            { "Vivid Violet", VividViolet},
            { "Vivid Yellow", VividYellow},
            { "Vodka", Vodka},
            { "Volt", Volt},

            { "Wageningen Green", WageningenGreen},
            { "Warm Black", WarmBlack},
            { "Water", Water},
            { "Watermelon", Watermelon},
            { "Watermelon Red", WatermelonRed},
            { "Waterspout", Waterspout},
            { "Weldon Blue", WeldonBlue},
            { "Wenge", Wenge},
            { "Wheat", Wheat},
            { "White", White},
            { "White Chocolate", WhiteChocolate},
            { "White Coffee", WhiteCoffee},
            { "White Smoke", WhiteSmoke},
            { "Wild Blue Yonder", WildBlueYonder},
            { "Wild Orchid", WildOrchid},
            { "Wild Strawberry", WildStrawberry},
            { "Wild Watermelon", WildWatermelon},
            { "Willpower Orange", WillpowerOrange},
            { "Windsor Tan", WindsorTan},
            { "Wine", Wine},
            { "Wine Red", WineRed},
            { "Wine Dregs", WineDregs},
            { "Winter Sky", WinterSky},
            { "Winter Wizard", WinterWizard},
            { "Wintergreen Dream", WintergreenDream},
            { "Wisteria", Wisteria},
            { "Wood Brown", WoodBrown},

            { "Xanadu", Xanadu},

            { "Yale Blue", YaleBlue},
            { "Yankees Blue", YankeesBlue},
            { "Yellow", Yellow},
            { "Yellow Crayola", YellowCrayola},
            { "Yellow Munsell", YellowMunsell},
            { "Yellow NCS", YellowNCS},
            { "Yellow Pantone", YellowPantone},
            { "Yellow Process", YellowProcess},
            { "Yellow RYB", YellowRYB},
            { "Yellow Green", YellowGreen},
            { "Yellow Green Crayola", YellowGreenCrayola},
            { "Yellow Greeen ColWheel", YellowGreeenColWheel},
            { "Yellow Orange", YellowOrange},
            { "Yellow Orange ColWheel", YellowOrangeColWheel},
            { "Yellow Rose", YellowRose},
            { "Yellow Sunshine", YellowSunshine},
            { "YInMn Blue", YInMnBlue},

            { "Zaffre", Zaffre},
            { "Zinnwaldite Brown", ZinnwalditeBrown},
            { "Zomp", Zomp},



        };

        public static Dictionary<string, Color> AllColors
        {
            get { return allColors; }
        }

        #endregion

        #region Public Properties


        /// <summary>
        /// Gets the color a.
        /// </summary>
        /// <value>The color a.</value>
        public static Dictionary<string, Color> ColorA
        {
            get { return allColors; }
        }

        #endregion

        #region Private Methods
        /**
		 * Get human readable name from a Color.
		 */

        /// <summary>
        /// Get Color Name
        /// </summary>
        /// <param name="InColor">Set in-color</param>
        /// <returns>System.String.</returns>
        public static string GetColorName(Color InColor)
        {
            Color lab = Color.FromArgb(InColor.R, InColor.G, InColor.B);

            string name = "Unknown";
            float diff = (float)double.PositiveInfinity;

            foreach (KeyValuePair<string, Color> kvp in allColors)
            {
                name = kvp.Key;
            }

            return name;
        }


        /// <summary>
        /// Gets the color.
        /// </summary>
        /// <param name="InColor">Color of the in.</param>
        /// <returns>Color.</returns>
        public static Color GetColor(Color InColor)
        {
            Color lab = Color.FromArgb(InColor.R, InColor.G, InColor.B);


            float diff = (float)double.PositiveInfinity;

            foreach (KeyValuePair<string, Color> kvp in allColors)
            {
                lab = kvp.Value;
            }

            return lab;
        }


        #endregion

    }
}
